#!/usr/bin/env node

let esbuild = require("esbuild");

/**
 * @type {esbuild.BuildOptions}
 */
let options = {
  entryPoints: ["src/index.ts"],
  bundle: true,
  target: ["es2020"],
  minify: true,
  sourcemap: true,
  loader: { ".png": "dataurl" },
  format: "esm",
  outdir: "dist",
};

if (require.main) {
  esbuild.buildSync(options);
}

module.exports = options;